/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface License {
    licenseOid: string;
    licenseAvailableSeats: number; 
    licenseName:string;
    licenseSerial:string;
    licensePurchasedSeats: number;
    assetCategoryOid: string;
    manufacturerOid:string;
    vendorOid: string;
    licensePurchaseDate:Date;
    licensePurchaseNumber:string;
    licensePurchaseCost:number;
    licenseContact:string;
    licenseRemarks:string;
    organizationOid: string;
    createdBy: string;
    createdOn: Date;
    updatedBy?: string;
    updatedOn?: Date;
}